// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drookwhbncntalnoukwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyb29rd2hibmNudGFsbm91a3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzg2MjMsImV4cCI6MjA2NTkxNDYyM30.qcO44_BU1sa2Ia-zx17iPcy90ilA6jIa8dzL52uXZ-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);